In [115]:
import pandas as pd 
import numpy as np
from bs4 import BeautifulSoup
import requests
import cloudscraper

In [153]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
}

In [154]:
url = "https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index.html"

In [118]:
#proxy = "117.36.76.86:8085"

In [155]:
scraper = cloudscraper.create_scraper()  # This handles the Cloudflare challenge

In [120]:
#scraper.proxies = {
 #   "http": f"http://{proxy}",
#}

In [ ]:
response = scraper.get(url, headers=headers)
response

In [157]:
response.encoding = 'utf-8'  # Set the encoding to 'gbk' for Chinese characters

In [158]:
soup = BeautifulSoup(response.text, 'html.parser')

In [159]:
articles = soup.find_all('div', class_='title')

In [160]:
len(articles)

20

In [161]:
Artiles = []
Links = []
Date = []

for article in articles:
    title = article.find('a', )
    link = article.find('a')['href']
    date_div = article.find_next_sibling('div', class_='more')
    if date_div:
        date_text = date_div.text.strip()
    else:
        date_text = 'No date available'
    Artiles.append(title.get_text(strip=True))
    Links.append(link)
    Date.append(date_text)

df = pd.DataFrame({
    'Article': Artiles,
    'Link': Links,
    'Date': Date,
})

df

,Article,Link,Date
0,十三届全国政协教科卫体委员会副主任刘慧接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202507/t20250718_435373.html,2025-07-18
1,陕西省西安市人大常委会党组书记、主任韩松接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202507/t20250714_434374.html,2025-07-14
2,湖北省政协原党组成员、副主席周先旺接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202507/t20250708_433089.html,2025-07-08
3,原中国中化集团有限公司党组成员、副总经理冯志斌接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202507/t20250704_432566.html,2025-07-04
4,中国东方航空集团有限公司原党组书记、董事长刘绍勇接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202506/t20250628_431325.html,2025-06-28
5,海南省委常委、秘书长倪强接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202506/t20250625_430717.html,2025-06-25
6,国家中医药管理局原局长于文明接受国家监委监察调查,../../../toutiaon/202506/t20250622_430023.html,2025-06-22
7,江西省政协原党组成员、副主席胡幼桃接受中央纪委国家监委纪律审查和监察调查,./202506/t20250619_429652.html,2025-06-19
8,广西壮族自治区政协原党组成员、副主席彭晓春接受中央纪委国家监委纪律审查和监察调查,./202506/t20250616_428784.html,2025-06-16
9,交通运输部党组成员，国家铁路局党组书记、局长费东斌接受中央纪委国家监委纪律审查和监察调查,./202506/t20250612_428314.html,2025-06-12
10,原中央防范和处理邪教问题领导小组办公室副主任高以忱接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202506/t20250609_427467.html,2025-06-09
11,十四届全国政协常委、经济委员会副主任毕井泉接受中央纪委国家监委纪律审查和监察调查,./202505/t20250529_425837.html,2025-05-29
12,国家国防科技工业局原党组成员、副局长张建华接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202505/t20250528_425418.html,2025-05-28
13,陕西省政协副主席刘宽忍接受国家监委监察调查,../../../toutiaon/202505/t20250525_424844.html,2025-05-25
14,四川省政府党组成员、副省长、省公安厅厅长叶寒冰接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202505/t20250521_424132.html,2025-05-21
15,广西壮族自治区党委副书记、自治区政府主席蓝天立接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202505/t20250516_423287.html,2025-05-16
16,国家林业和草原局原党组成员、副局长李春良接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202505/t20250513_422609.html,2025-05-13
17,中国一重集团有限公司党委常委、副总经理陆文俊接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202505/t20250509_422021.html,2025-05-09
18,中国证券监督管理委员会党委委员、副主席王建军接受中央纪委国家监委纪律审查和监察调查,./202504/t20250430_420820.html,2025-04-30
19,四川省人大常委会原党组成员、副主任宋朝华接受中央纪委国家监委纪律审查和监察调查,../../../toutiaon/202504/t20250425_419509.html,2025-04-25

In [128]:
#df.to_csv('articles.csv', index=False, encoding='utf-8-sig')

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Article  20 non-null     object
 1   Link     20 non-null     object
 2   Date     20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [130]:
print('十三届全国政协教科卫体委员会副主任刘慧接受中央纪委国家监委纪律审查和监察调查')

十三届全国政协教科卫体委员会副主任刘慧接受中央纪委国家监委纪律审查和监察调查

In [188]:
import pandas as pd
from bs4 import BeautifulSoup
import cloudscraper

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
}

Artiles = []
Links = []
Date = []

scraper = cloudscraper.create_scraper()

for p in range(0, 22):
    url = f"https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index_{p}.html"
    response = scraper.get(url, headers=headers)
    response.encoding = 'utf-8'
    soup = BeautifulSoup(response.text, 'html.parser')
    articles = soup.find_all('li')

    for article in articles:
        title = article.select_one('div.title a ')
        link = article.select_one('div.title a')['href']
        date_div = article.select_one('div.more ')
        if date_div:
            date_text = date_div.text.strip()
        else:
            date_text = 'No date available'
        Artiles.append(title.get_text(strip=True))
        Links.append(link)
        Date.append(date_text)

df = pd.DataFrame({
    'Article': Artiles,
    'Link': Links,
    'Date': Date,
})

df.to_csv('articles_shorts.csv', index=False, encoding='utf-8-sig')

In [191]:
import pandas as pd
from bs4 import BeautifulSoup
import cloudscraper
import time
import random
from urllib.parse import urljoin

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
}

Artiles = []
Links = []
Date = []

def scrape_page(url, scraper):
    response = scraper.get(url, headers=headers)
    response.encoding = 'utf-8'
    soup = BeautifulSoup(response.text, 'html.parser')
    count = 0
    for li in soup.select('li:has(div.title)'):
        title_div = li.find('div', class_='title')
        a_tag = title_div.find('a') if title_div else None
        if not a_tag:
            continue
        title = a_tag.get_text(strip=True)
        # Always join with the current page's URL for robustness
        link = urljoin(url, a_tag.get('href', ''))
        date_div = li.find('div', class_='more')
        date_text = date_div.text.strip() if date_div else 'No date available'
        Artiles.append(title)
        Links.append(link)
        Date.append(date_text)
        count += 1
    print(f"Scraped {count} articles from {url}")

start_page = 0
end_page = 4  # Set as needed
batch_size = 2

current = start_page
while current <= end_page:
    # Create a new cloudscraper session for each batch
    scraper = cloudscraper.create_scraper()
    for p in range(current, min(current + batch_size, end_page + 1)):
        if p == 0:
            url = "https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index.html"
        else:
            url = f"https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index_{p}.html"
        scrape_page(url, scraper)
        time.sleep(random.uniform(2, 3))  # Wait 2-5 seconds between pages
    current += batch_size
    print("Waiting 5 seconds before next batch...")
    time.sleep(5)  # Wait 5 seconds

df = pd.DataFrame({
    'Article': Artiles,
    'Link': Links,
    'Date': Date,
})

print(f"Total articles scraped: {len(df)}")
df.to_csv('articles.csv', index=False, encoding='utf-8-sig')
df

Scraped 20 articles from https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index.html
Scraped 20 articles from https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index_1.html
Waiting 5 seconds before next batch...
Scraped 20 articles from https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index_2.html
Scraped 20 articles from https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index_3.html
Waiting 5 seconds before next batch...
Scraped 20 articles from https://www.ccdi.gov.cn/scdcn/zggb/zjsc/index_4.html
Waiting 5 seconds before next batch...
Total articles scraped: 100

,Article,Link,Date
0,十三届全国政协教科卫体委员会副主任刘慧接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/toutiaon/202507/t20250...,2025-07-18
1,陕西省西安市人大常委会党组书记、主任韩松接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/toutiaon/202507/t20250...,2025-07-14
2,湖北省政协原党组成员、副主席周先旺接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/toutiaon/202507/t20250...,2025-07-08
3,原中国中化集团有限公司党组成员、副总经理冯志斌接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/toutiaon/202507/t20250...,2025-07-04
4,中国东方航空集团有限公司原党组书记、董事长刘绍勇接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/toutiaon/202506/t20250...,2025-06-28
...,...,...,...
95,河北省纪委副书记、省监委副主任陈玉祥接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/toutiaon/202312/t20231...,2023-12-09
96,黑龙江省委常委、副省长王一新接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/toutiaon/202312/t20231...,2023-12-08
97,四川省政协原党组成员、副主席杨克宁接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/scdcn/zggb/zjsc/202311...,2023-11-16
98,中粮集团有限公司原党组成员、副总经理周政接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/scdcn/zggb/zjsc/202311...,2023-11-08
99,中国工商银行原党委委员、副行长张红力接受中央纪委国家监委纪律审查和监察调查,https://www.ccdi.gov.cn/scdcn/zggb/zjsc/202311...,2023-11-04

In [190]:
df['Link']

0     https://www.ccdi.gov.cn/toutiaon/202507/t20250...
1     https://www.ccdi.gov.cn/toutiaon/202507/t20250...
2     https://www.ccdi.gov.cn/toutiaon/202507/t20250...
3     https://www.ccdi.gov.cn/toutiaon/202507/t20250...
4     https://www.ccdi.gov.cn/toutiaon/202506/t20250...
                            ...
95    https://www.ccdi.gov.cn/toutiaon/202312/t20231...
96    https://www.ccdi.gov.cn/toutiaon/202312/t20231...
97    https://www.ccdi.gov.cn/202311/t20231116_30807...
98    https://www.ccdi.gov.cn/202311/t20231108_30610...
99    https://www.ccdi.gov.cn/202311/t20231104_30512...
Name: Link, Length: 100, dtype: object

In [2]:
# aliexpress_scraper.py

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time
import pandas as pd

def scrape_aliexpress(keyword, max_products=20):
    options = Options()
    options.add_argument("--headless=new")  # Run in background
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')

    driver = webdriver.Chrome(options=options)
    search_url = f"https://www.aliexpress.com/wholesale?SearchText={keyword.replace(' ', '%20')}"
    driver.get(search_url)

    time.sleep(5)  # Wait for page to load

    titles, prices, orders, ratings, urls = [], [], [], [], []

    products = driver.find_elements(By.CSS_SELECTOR, ".manhattan--container--1lP57Ag")[:max_products]

    for product in products:
        try:
            title = product.find_element(By.CSS_SELECTOR, ".manhattan--titleText--WccSjUS").text
            price = product.find_element(By.CSS_SELECTOR, ".manhattan--price-sale--1CCSZfK").text
            order_text = product.find_element(By.CSS_SELECTOR, ".manhattan--trade--2PeJIEi").text
            rating = product.find_element(By.CSS_SELECTOR, ".manhattan--rating--2nUIRY6").text
            link = product.find_element(By.TAG_NAME, 'a').get_attribute("href")

            titles.append(title)
            prices.append(price)
            orders.append(order_text)
            ratings.append(rating)
            urls.append(link)

        except Exception as e:
            continue

    driver.quit()

    df = pd.DataFrame({
        'Title': titles,
        'Price': prices,
        'Orders': orders,
        'Rating': ratings,
        'URL': urls
    })

    df.to_csv("aliexpress_products.csv", index=False)
    print(f"\n✅ {len(df)} products saved to 'aliexpress_products.csv'")

# Run the scraper
if __name__ == "__main__":
    keyword = input("Enter product keyword (e.g., smart LED): ")
    scrape_aliexpress(keyword)

✅ 0 products saved to 'aliexpress_products.csv'